---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kettle-pvc
  # namespace: webspoon
spec:
  accessModes:
    #- ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pentaho-pvc
  # namespace: webspoon
spec:
  accessModes:
    #- ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
