---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: webspoon-pvc
  namespace: webspoon
spec:
  accessModes:
    #- ReadWriteMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
